FROM python:3.10-alpine as compiler

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"


COPY requirements.txt .

RUN apk update \
    && apk add --no-cache --virtual .build-deps gcc g++ \
    && apk add --no-cache postgresql-client git \
    && pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade -r requirements.txt


FROM python:3.10-alpine as runner

WORKDIR /usr/src

RUN apk add --no-cache nodejs npm
COPY --from=compiler /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY . .

RUN ["chmod", "+x", "/usr/src/entrypoint.dev.sh"]
ENTRYPOINT ["/usr/src/entrypoint.dev.sh"]