services:
    postgres_dev:
        image: postgres:15-alpine
        volumes:
            - portfolio_postgres_data_v4:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=mydatabase
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres_dev
    p_backend_dev:
        build:
            dockerfile: Dockerfile.dev
        command: sh -cx "python manage.py tailwind start & python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/usr/src
        ports:
            - 8989:8000
        environment:
            - DEBUG=True
            - PORT=8000
            - ALLOWED_HOSTS=localhost
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=mydatabase
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres_dev
        # Without tty, no stdin, and tailwind watcher aborts
        # https://github.com/tailwindlabs/tailwindcss/issues/5324
        tty: true
        depends_on:
            - postgres_dev

volumes:
    portfolio_postgres_data_v4:
