# Generated by Django 4.0.6 on 2022-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='portfolio/img')),
            ],
        ),
    ]
