# Generated by Django 4.0.6 on 2022-07-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.FileField(upload_to='logo')),
                ('type', models.CharField(choices=[('L', 'LANGUAGE'), ('F', 'FRAMEWORK'), ('P', 'PLATFORM')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='project/image')),
                ('url', models.URLField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('technologies', models.ManyToManyField(to='portfolio.technology')),
            ],
        ),
    ]
