# Generated by Django 4.1.1 on 2022-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('L', 'LANGUAGE'), ('BE', 'BACKEND'), ('FE', 'FRONTEND'), ('P', 'PLATFORM')], max_length=2),
        ),
    ]
