# Generated by Django 4.1.5 on 2024-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.FileField(upload_to='logo/v2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/v2'),
        ),
    ]
